### ISSUE TITLE
DW1820a 智能WiFi热点可以连接吗？

### ISSUE THREAD

**Issue by ettingshausen** [Hush-vv/Hackintosh-AsRock-Z490-Phantom-Gaming-ITX-TB3-intel-10850k-OpenCorePkg#1]
> acidanthera/bugtracker/issues/1571    

 同样的问题，接力、AirDrop都是正常的就是热点无法连接。偶尔可以连的上（极小概率）。

**Comment by Hush-vv** [comment]
这卡就这样了，没有人维护这功能。想智能热点只能换白果卡
