### ISSUE TITLE
最新的12.0系统USB端口失效了。

### ISSUE THREAD

**Issue by zhaianan** [Hush-vv/Hackintosh-AsRock-Z490-Phantom-Gaming-ITX-TB3-intel-10850k-OpenCorePkg#2]
使用目前最新的USBmap并不能驱动usb

**Comment by Hush-vv** [comment]
我的正常啊
<img width="870" alt="QQ20211005-002101@2x" src="https://user-images.githubusercontent.com/61744850/135888131-eba0aae4-fa6d-4c34-baa5-35c20c496d7e.png">

**Comment by zhaianan** [comment]
你可以试下u盘，完全不能读取识别

**Comment by Hush-vv** [comment]
我的是假U盘
<img width="975" alt="QQ20211005-191942@2x" src="https://user-images.githubusercontent.com/61744850/136013454-807dba9f-2a55-4d96-ae3a-ce1486654ff1.png">
？

**Comment by Hush-vv** [comment]
需要打开XhciPortLimit并替
[USBMap.kext.zip](https://github.com/Hush-vv/Hackintosh-AsRock-Z490-Phantom-Gaming-ITX-TB3-intel-10850k-OpenCorePkg/files/7290994/USBMap.kext.zip)
换它

**Comment by zhaianan** [comment]
好的，

> 需要打开XhciPortLimit并替
> [USBMap.kext.zip](https://github.com/Hush-vv/Hackintosh-AsRock-Z490-Phantom-Gaming-ITX-TB3-intel-10850k-OpenCorePkg/files/7290994/USBMap.kext.zip)
> 换它

感谢，我回去试试
