### ISSUE TITLE
dw1820a相关问题

### ISSUE THREAD

**Issue by zcgg2zhmm** [Hush-vv/Hackintosh-AsRock-Z490-Phantom-Gaming-ITX-TB3-intel-10850k-OpenCorePkg#5]
首先感谢您的分享，这里我反馈一些问题。
1. 好像收不到5G信号？
2. 蓝牙貌似也不稳定，连上耳机容易断开，或者压根收不到耳机？

**Comment by ChisBread** [comment]
1. brcmfx-country=#a 以及特定频段的5G信号可能永远收不到，可以试试改变Wi-Fi频段
2. 优先考虑天线等物理问题；按住opt单击蓝牙图标，可以看到信号强度等信息
3. 反馈问题时请给出足够的信息，包括不限于硬件信息、日志等

**Comment by zcgg2zhmm** [comment]
> 1. brcmfx-country=#a 以及特定频段的5G信号可能永远收不到，可以试试改变Wi-Fi频段
> 2. 优先考虑天线等物理问题；按住opt单击蓝牙图标，可以看到信号强度等信息
> 3. 反馈问题时请给出足够的信息，包括不限于硬件信息、日志等

谢谢~
改了路由器的频段，可以了。
蓝牙也行了，很诡异！
