### ISSUE TITLE
我的总是转彩虹圈圈圈 有人有吗？是硬盘问题吗？

### ISSUE THREAD

**Issue by qinkangdeid** [Hush-vv/Hackintosh-AsRock-Z490-Phantom-Gaming-ITX-TB3-intel-10850k-OpenCorePkg#9]
## 电脑配置
|规格 | 详细信息|
|:-: | :-:|
|主板| AsRock Z490 Phantom Gaming ITX/TB3 |
|操作系统| **macOS** Ventura 13.2.1 |
|处理器| Intel Core 10700k  |
|内存| 海盗船32GB |
|硬盘| 三星980 pro 1T |
|显卡| Intel UHD Graphics 630 / Sapphire RX 6600XT |
|显示器|Dell U2720QM  4K |
|声卡| Realtek ALC1220 |
|网卡| BCM943602CS |
|SMBIOS| iMac20,2 |

**Comment by Hush-vv** [comment]
显卡超频了吗，都默认试试看

**Comment by qinkangdeid** [comment]
我。。重装系统 全部抹掉重装现在看 好像好了。。。。
